#!/bin/bash

if ! command -v node
then
    echo Installing nodejs...
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    sudo apt-get install -y nodejs
    echo Switching to stable...
    sudo npm install -g n
    sudo n stable
fi

if ! command -v zsh
then
    echo Installing Zsh...
    sudo apt-get install -y zsh
    chsh -s $(which zsh)
fi

if [[ ! -d ~/.oh-my-zsh ]]
then
    echo Installing Oh My Zsh...
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ ! -d ~/.oh-my-zsh/custom/themes/powerlevel10k ]]
then
    echo Installing Powerlevel10k zsh theme...
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

if [[ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]]
then
    echo Installing zsh-syntax-highlighting plugin...
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

