#!/bin/bash

if ! command -v node > /dev/null
then
    echo Installing nodejs...
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    sudo apt-get install -y nodejs
    echo Switching to stable...
    sudo npm install -g n
    sudo n stable
fi

if ! command -v apt-add-repository > /dev/null
then
    echo Installing apt-add-repository...
    sudo apt-get install -y software-properties-common
fi

if ! command -v zsh > /dev/null
then
    echo Installing Zsh...
    sudo apt-get install -y zsh
    chsh -s $(which zsh)
fi

if [[ ! -d ~/.oh-my-zsh ]]
then
    echo Installing Oh My Zsh...
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ ! -d ~/.oh-my-zsh/custom/themes/powerlevel10k ]]
then
    echo Installing Powerlevel10k zsh theme...
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

if [[ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]]
then
    echo Installing zsh-syntax-highlighting plugin...
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

if ! command -v nvim > /dev/null
then
    echo Installing Neovim...
    sudo add-apt-repository ppa:neovim-ppa/stable
    sudo apt-get install -y neovim
fi

echo Installing Neovim plugins...
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim --headless +PlugInstall +qall

if ! command -v gh > /dev/null
then
    echo Installing GitHub CLI...
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt install gh -y
fi

